<?php

    namespace common\models;

    use Yii;
    use yii\db\ActiveRecord;

    /**
     * This is the model class for table "messages".
     *
     * @property int $id
     * @property string $name
     * @property string $date
     * @property int $moder
     * @property string $message
     * @property string $email
     */
    class Messages extends ActiveRecord
    {
        /**
         * {@inheritdoc}
         */
        public static function tableName()
        {
            return 'messages';
        }

        /**
         * {@inheritdoc}
         */
        public function rules()
        {
            return [
                [['name', 'date', 'message', 'email'], 'required'],
                [['date'], 'safe'],
                [['moder'], 'integer'],
                [['message'], 'string'],
                [['name', 'email'], 'string', 'max' => 255],
            ];
        }

        /**
         * {@inheritdoc}
         */
        public function attributeLabels()
        {
            return [
                'id'      => Yii::t('app', 'ID'),
                'name'    => Yii::t('app', 'Name'),
                'date'    => Yii::t('app', 'Date'),
                'moder'   => Yii::t('app', 'Moder'),
                'message' => Yii::t('app', 'Message'),
                'email'   => Yii::t('app', 'Email'),
            ];
        }

        public function save($runValidation = true, $attributeNames = null)
        {
            $isInsert = $this->isNewRecord;
            if ($isInsert) {
                $this->date = date("Y-m-d H:i:s");
            }

            return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        }
    }
